import librerias as l

num1 = int(input("Ingrese numero 1"))
num2 = int(input("Ingrese numero 2"))
resultado = l.suma(num1, num2)
print("La suma es ",resultado)
resultado = l.resta(num1, num2)
print("La resta es ",resultado)
resultado = l.multiplicacion(num1, num2)
print("La multiplicacion es ",resultado)
resultado = l.division(num1, num2)
print("La division es ",resultado)
resultado = l.sumatoriaIterativa(num1)
print("La sumatoria es ", resultado)
resultado = l.potenciaIterativa(num1,num2)
print("La potencia es ", resultado)
